<a href="https://colab.research.google.com/github/Aditi7007/Advance-Python/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
dataset=pd.read_csv("/content/churn.csv")

In [ ]:
dataset

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.20,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.70,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.30,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.10,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.30,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

In [ ]:
sf5=pd.DataFrame((
    "Name":["john","aditi","alpa","henry,],
    "Marks"